color_scheme: pdpa

title: PERSONAL DATA PROTECTION BILL, 2019

email: georgejpadayatti@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Bill to provide for protection of the privacy of individuals relating to their personal data,
  specify the flow and usage of personal data, create a relationship of trust between
  persons and entities processing the personal data, protect the rights of individuals
  whose personal data are processed, to create a framework for organisational and
  technical measures in processing of data, laying down norms for social media
  intermediary, cross-border transfer, accountability of entities processing personal
  data, remedies for unauthorised and harmful processing, and to establish a Data
  Protection Authority of India for the said purposes and for matters connected therewith
  or incidental thereto.


domain: "pdpa-info.github.io"

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://pdpa-info.in" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

twitter_username: georgepadayatti

github_username:  georgejpadayatti

# Build settings
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed

heading_anchors: true

footer_content: ""

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/georgejpadayatti/pdpa-info.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately